version: "3.6"
services:

  api:
    build: .
    environment:
      DATABASE_NAME: "orava"
      IP_SERVER: "45.82.68.203"
      PORT_SERVER: 10050
      IP_SERVER_FILES: "45.82.68.203"
      PORT_SERVER_FILES: 10020

    volumes:
      - ./:/main
    ports:
      - "10020:10020"
    network_mode: "host"
